"""
config.py
=========
DO NOT EDIT THIS FILE.

All your settings live in  SETTINGS.py  — open that file instead.

This file simply re-exports everything from SETTINGS.py so that the
rest of the code (renderer.py, audio_engine.py, etc.) can still do
    import config
    config.WIDTH
without any changes.
"""
from SETTINGS import *  # noqa: F401, F403
