"""
config.py
=========
DO NOT EDIT THIS FILE.

All your settings live in  SETTINGS_PROFESSIONAL.py  — open that file instead.

This file simply re-exports everything from SETTINGS_PROFESSIONAL.py so that the
rest of the code (audio_engine.py, etc.) can still do
    import config
    config.WIDTH
without any changes.
"""
from SETTINGS_PROFESSIONAL import *  # noqa: F401, F403
