"""
QURAN VIDEO GENERATOR - AUTO-GENERATED SETTINGS
"""

SURAH_NUMBER = 4
PREFERRED_RECITER = "alafasy"
AYAH_START = 1
AYAH_END = 10
FAST_MODE = False

ARABIC_CENTER_Y = 800
ARABIC_X_MARGIN = 89
ARABIC_LINE_GAP = 52
ARABIC_WORD_GAP = 28

ENGLISH_Y_START = 1050
ENGLISH_X_MARGIN = 95
ENGLISH_LINE_GAP = 44
REFERENCE_Y = 1740

ARABIC_FONT_SIZE = 72
ENGLISH_FONT_SIZE = 42
REFERENCE_FONT_SIZE = 29

AUTO_CONTRAST = True
ARABIC_DEFAULT_COLOR = (255, 255, 255, 255)
ENGLISH_DEFAULT_COLOR = (255, 255, 255, 255)
REFERENCE_COLOR = (220, 220, 220, 255)
ARABIC_HIGHLIGHT_COLOR = (220, 40, 20, 255)
ENGLISH_HIGHLIGHT_COLOR = (51, 203, 184, 255)
TEXT_STROKE_WIDTH = 2

LOGO_MAX_W = 160
LOGO_MARGIN_X = 48
LOGO_MARGIN_Y = 48

REEL_TARGET_SEC = 16
REEL_MIN_SEC = 14
REEL_MAX_SEC = 18
YOUTUBE_TARGET_MIN = 4.5
YOUTUBE_MIN_SEC = 240
YOUTUBE_MAX_SEC = 300
HOLD_AT_END = 1.5

GENERATE_PHONE_FORMAT = True
GENERATE_TV_FORMAT = True

FPS = 30
BG_CHANGE_INTERVAL = 2

ARABIC_FONT_PATH = "fonts/Amiri-Bold.ttf"
ARABIC_FONT_FALLBACK = "fonts/Amiri-Regular.ttf"
ENGLISH_FONT_PATH = "fonts/NotoSans-SemiBold.ttf"
ENGLISH_FONT_FALLBACK = "fonts/dejavu-sans.extralight.ttf"
REFERENCE_FONT_PATH = "fonts/NotoSans-Regular.ttf"

AUDIO_CACHE_DIR = "audio/recitations"
REEL_OUTPUT_DIR = "videos/reels"
YOUTUBE_OUTPUT_DIR = "videos/youtube"
IMAGES_DIR = "images"
CONTENT_FILE = "content/surah.json"

AUDIO_SR = 22050
ONSET_DELTA = 0.07
MIN_WORD_DURATION = 0.12
MIN_ONSET_GAP = 0.06
ENERGY_THRESHOLD = 0.018

WIDTH = 1080
HEIGHT = 1920
